### ISSUE TITLE
make a callback when we receive frames and when we do not

### ISSUE THREAD

**Issue by simorautiainen** [SiiliCam/NDIWrapper#1]

**Comment by JoniSuominen** [comment]
haloo

**Comment by JoniSuominen** [comment]
voitko tehdä jo haloo

**Comment by JoniSuominen** [comment]
| Header | Header | Header | Header | Header |
|--------|--------|--------|--------|--------|
| Cell | Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell | Cell |
